Repository StackStorm/st2chatops, pull requests merged in 2020-07, with the labels that each got.

#153 Remove EL6 from st2chatops
  .circleci/config.yml
  docker-compose.yml
  packagingenv/Dockerfile.template
  packagingenv/centos6/Dockerfile
  packagingenv/centos6/docker-entrypoint.sh
  rpm/st2chatops.init
  rpm/st2chatops.spec
  testingenv/centos6/Dockerfile
  testingenv/centos6/docker-entrypoint.sh
Labels: breaking change, enhancement

#154 Remove HipChat adapter
  Makefile
  README.md
  npm-shrinkwrap.json
  package.json
  packagingenv/Dockerfile.template
  packagingenv/centos8/Dockerfile
  st2chatops.env
Labels: enhancement, maintenance

#156 Bump version in npm-shrinkwrap.json
  .circleci/config.yml
  npm-shrinkwrap.json
Labels: maintenance
